import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CharacterProvider } from "@/lib/CharacterContext";
import { PeriodProvider } from "@/lib/PeriodContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Providers must sit above the page components so useCharacter() /
            usePeriod() inside pages resolve to real values, not context defaults */}
        <CharacterProvider>
          <PeriodProvider>{children}</PeriodProvider>
        </CharacterProvider>
      </body>
    </html>
  );
}
